fix indent, trailing space, and so on

diff --git a/root/etc/cont-init.d/50-rclone b/root/etc/cont-init.d/50-rclone
--- a/root/etc/cont-init.d/50-rclone
+++ b/root/etc/cont-init.d/50-rclone
@@ -2,23 +2,23 @@
 . /usr/local/bin/variables
 
 if [[ -z $RCLONE_REMOTE_PATH ]]; then
-	echo "*** RCLONE_REMOTE_PATH not set. Exiting..."
-	exit 1
+    echo "*** RCLONE_REMOTE_PATH not set. Exiting..."
+    exit 1
 fi
 
 if [[ ! "${RCLONE_REMOTE_PATH}" == :* ]]; then
-	# if not using connection strings for remote path
-	until [ -f "${RCLONE_CONFIG}" ]; do
-		echo "Waiting for '"${RCLONE_CONFIG}"'. Retrying in 30s ..."
-		echo "RUN: docker exec -it <DOCKER_CONTAINER> rclone_setup"
-		sleep 30
-	done
+    # if not using connection strings for remote path
+    until [ -f "${RCLONE_CONFIG}" ]; do
+        echo "Waiting for '"${RCLONE_CONFIG}"'. Retrying in 30s ..."
+        echo "RUN: docker exec -it <DOCKER_CONTAINER> rclone_setup"
+        sleep 30
+    done
 fi
 
 echo "*** checking rclone remote path: ${RCLONE_REMOTE_PATH}"
 if [[ ! "${RCLONE_REMOTE_PATH}" == *:* ]]; then
-	echo "ERROR: Missing colon (:) in RCLONE_REMOTE_PATH (${RCLONE_REMOTE_PATH})"
-	exit 1
+    echo "ERROR: Missing colon (:) in RCLONE_REMOTE_PATH (${RCLONE_REMOTE_PATH})"
+    exit 1
 fi
 if [[ ! "${RCLONE_REMOTE_PATH}" == :* ]]; then
     rclone_remote="$(echo $RCLONE_REMOTE_PATH | cut -d: -f1):"
@@ -31,7 +31,7 @@ fi
 
 echo "*** checking rclone mountpoint: ${rclone_mountpoint}"
 while findmnt "${rclone_mountpoint}" | grep -q fuse.rclone; do
-	echo "ERROR: rclone mountpoint (${rclone_mountpoint}) already mounted"
+    echo "ERROR: rclone mountpoint (${rclone_mountpoint}) already mounted"
     fusermount -uz "${rclone_mountpoint}"
     echo "Retrying in 30s ..."
     sleep 30s
