add new tag: mod
* cron by go-cron
* add cont-init.d scripts: install-pkg, wait-for-mnt
* add rclone_refresh script

diff --git a/root/etc/cont-init.d/50-rclone b/root/etc/cont-init.d/50-rclone
--- a/root/etc/cont-init.d/50-rclone
+++ b/root/etc/cont-init.d/50-rclone
@@ -1,28 +1,43 @@
 #!/usr/bin/with-contenv bash
+. /usr/local/bin/variables
 
-echo "*** checking rclone.conf"
-while [ ! -f "/config/rclone.conf" ]; do
-	echo "Waiting for rclone configuration file in /config/rclone.conf. Retrying in 30s ..."
-	echo "RUN: docker exec -it <DOCKER_CONTAINER> rclone_setup"
-	sleep 30
+if [[ -z $RCLONE_REMOTE_PATH ]]; then
+	echo "*** RCLONE_REMOTE_PATH not set. Exiting..."
+	exit 1
+fi
+
+if [[ ! "${RCLONE_REMOTE_PATH}" == :* ]]; then
+	# if not using connection strings for remote path
+	until [ -f "${RCLONE_CONFIG}" ]; do
+		echo "Waiting for '"${RCLONE_CONFIG}"'. Retrying in 30s ..."
+		echo "RUN: docker exec -it <DOCKER_CONTAINER> rclone_setup"
+		sleep 30
+	done
+fi
+
+echo "*** checking rclone remote path: ${RCLONE_REMOTE_PATH}"
+if [[ ! "${RCLONE_REMOTE_PATH}" == *:* ]]; then
+	echo "ERROR: Missing colon (:) in RCLONE_REMOTE_PATH (${RCLONE_REMOTE_PATH})"
+	exit 1
+fi
+if [[ ! "${RCLONE_REMOTE_PATH}" == :* ]]; then
+    rclone_remote="$(echo $RCLONE_REMOTE_PATH | cut -d: -f1):"
+    if ! rclone listremotes | grep -q "${rclone_remote}"; then
+        echo "ERROR: Invalid rclone remote name (${rclone_remote})"
+        echo "ERROR: Available rclone remotes ($(echo $(rclone listremotes) | tr -d '\r'))"
+        exit 1
+    fi
+fi
+
+echo "*** checking rclone mountpoint: ${rclone_mountpoint}"
+while findmnt "${rclone_mountpoint}" | grep -q fuse.rclone; do
+	echo "ERROR: rclone mountpoint (${rclone_mountpoint}) already mounted"
+    fusermount -uz "${rclone_mountpoint}"
+    echo "Retrying in 30s ..."
+    sleep 30s
 done
 
-echo "*** checking rclone remote path"
-rclone_remote_path=$(printenv RCLONE_REMOTE_PATH | tr -d '"' | tr -d "'")
-if [[ ! "${rclone_remote_path}" == *:* ]]; then
-	echo "ERROR: Missing colon (:) in RCLONE_REMOTE_PATH (${rclone_remote_path})"
-	exit 1
-fi
-rclone_remote="$(echo $rclone_remote_path | cut -d : -f 1):"
-if [ "$(rclone listremotes --config /config/rclone.conf | grep "${rclone_remote}" | wc -l)" == "0" ]; then
-	echo "ERROR: Invalid rclone remote name (${rclone_remote})"
-	echo "ERROR: Available rclone remotes ($(echo $(rclone listremotes --config /config/rclone.conf) | tr -d '\r'))"
-	exit 1
-fi
-
-echo "*** checking rclone mountpoint"
-rclone_mountpoint=$(if ! mountpoint -q /local; then echo /data; else echo /cloud; fi)
-if [ $(findmnt ${rclone_mountpoint} | grep fuse.rclone | wc -l) != "0" ]; then
-	echo "ERROR: rclone mountpoint (${rclone_mountpoint}) already mounted"
-	exit 1
-fi
+# permissions
+chown -R abc:abc \
+    /config /log /cloud /data
+chown abc:abc /cache /local
